### ISSUE TITLE
Windows for Gen 2

### ISSUE THREAD

**Issue by ad-m** [hyperonecom/h1-images-recommended#9]
See #8 for previous discussion in area.

For gen2 we need make Windows compatible with UEFI. Ideally, it would be to develop a hybrid Windows image for Gen 2.

> Let’s note an important fact that you always have to keep in mind: it is possible to boot Windows x64 from a GPT disk only on the UEFI-based system.
> Thus, if your PC is BIOS-based and you need to have a disk containing a GPT partition table, the easiest way is to add another MBR hard disk (standard or SSD), install Windows on it and then boot from this disk.

http://woshub.com/booting-windows-7-from-a-gpt-disk-using-bios-firmware-non-uefi/

> Windows Boot Manager does not support booting into Legacy BIOS mode on GPT disks. AIO Boot uses wimboot to do this.

https://www.aioboot.com/en/gpt-legacy/

**Comment by pbogu** [comment]
Are you willing to use third party boot manager? My approach would be to keep install as vanilla as possible and just use two different isos/answer files for Gen1 and Gen2 (MBR vs GPT)
